version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "github.com/opencontainers/runc"
      - dependency-name: "github.com/containerd/containerd"
    groups:
      backend:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: npm
    directory: /.github/linters
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /deployment/urunc-deploy
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
